server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-vod # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M

aliyun:
  vod:
    keyId: LTAI4GKGWm75WPLNWDznoG2P
    keySecret: bQjjLBz7qxG8deiNRaqGt9tBSemBgA
    templateGroupId: 9295c2638410cf79c3e565972327942b
    workflowId: 你配置的工作流id #工作流id
